name: Deploy Terragrunt infrastructure
on:
  pull_request:

permissions:
  id-token: write
  contents: read

env:
  TG_VERSION: '0.72.5'
  TF_VERSION: '1.10.5'
  TERRAGRUNT_EXCLUDE_DIR: "**/*/oidc"
  TERRAGRUNT_NON_INTERACTIVE: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: frontend-stage
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Authenticate to AWS
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.GH_IAM_ROLE_ARN }}
          output-credentials: true
      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tg_version: ${{ env.TG_VERSION }}
          tf_version: ${{ env.TF_VERSION }}
          tg_comment: true
          tg_dir: ${{ env.TG_DIR }}
          tg_command: 'run-all plan'
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.creds.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.creds.outputs.aws-secret-access-key }}
          TG_BUCKET_PREFIX: ${{ secrets.TG_BUCKET_PREFIX }}
  deploy:
    runs-on: ubuntu-latest
    environment: frontend-stage
    needs: [ plan ]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Authenticate to AWS
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume:  ${{ secrets.GH_IAM_ROLE_ARN }}
          output-credentials: true
      - name: Deploy
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tg_version: ${{ env.TG_VERSION }}
          tf_version: ${{ env.TF_VERSION }}
          tg_comment: true
          tg_command: 'run-all apply'
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.creds.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.creds.outputs.aws-secret-access-key }}
          TG_BUCKET_PREFIX: ${{ secrets.TG_BUCKET_PREFIX }}