name: Trigger Terragrunt infrastructure planning
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  detect-changed:
    name: Detect infrastructure changes
    uses: nestrr/flock-infra/.github/workflows/detect-infra-changes.yaml@main
    secrets: inherit
  trigger-deploy-fe-stage:
    needs: detect-changed
    name: Trigger frontend-stage plan if needed
    if: needs.detect-changed.outputs.fe-stage-changes == 'true'
    uses: nestrr/flock-infra/.github/workflows/plan.yaml@main
    with:
      actions_environment: "frontend-stage"
      tg_include_dir: "infra/frontend/live/stage"
    secrets: inherit
  trigger-deploy-fe-prod:
    needs: detect-changed
    name: Trigger frontend-prod plan if needed
    if: needs.detect-changed.outputs.fe-prod-changes == 'true'
    uses: nestrr/flock-infra/.github/workflows/plan.yaml@main
    with:
      actions_environment: "frontend-prod"
      tg_include_dir: "infra/frontend/live/prod"
    secrets: inherit
  trigger-deploy-be-stage:
    needs: detect-changed
    name: Trigger backend-stage plan if needed
    if: needs.detect-changed.outputs.be-stage-changes == 'true'
    uses: nestrr/flock-infra/.github/workflows/plan.yaml@main
    with:
      actions_environment: "backend-stage"
      tg_include_dir: "infra/backend/live/stage"
    secrets: inherit
  trigger-deploy-be-prod:
    needs: detect-changed
    name: Trigger backend-stage plan if needed
    if: needs.detect-changed.outputs.be-prod-changes == 'true'
    uses: nestrr/flock-infra/.github/workflows/plan.yaml@main
    with:
      actions_environment: "backend-prod"
      tg_include_dir: "infra/backend/live/prod"
    secrets: inherit